export const PREFERENCE_OPTIONS = [
  { id: 'LIGHT', label: '담백한 맛', emoji: '🥗' },
  { id: 'NO_PORK', label: '돼지고기 비선호', emoji: '🚫' },
  { id: 'OILY', label: '기름진 음식 OK', emoji: '🍤' },
  { id: 'RAW_OK', label: '회·사시미 좋아함', emoji: '🍣' },
  { id: 'SALTY', label: '짠 맛 선호', emoji: '🧂' },
  { id: 'SPICY_HIGH', label: '아주 매운 편', emoji: '🔥' },
  { id: 'SPICY_LOW', label: '약간 매운 편', emoji: '🌶️' },
  { id: 'SPICY_MED', label: '보통 매움', emoji: '🌶️' },
  { id: 'SWEET', label: '단 맛 선호', emoji: '🍰' },
  { id: 'VEGETARIAN', label: '채식 위주', emoji: '🥬' },
] as const;

export const PREFERENCE_LABELS: Record<string, string> = {
  ...Object.fromEntries(PREFERENCE_OPTIONS.map((p) => [p.id, p.label])),
  spicy: '매운맛',
  japanese: '일식',
  chinese: '중식',
  korean: '한식',
  western: '양식',
  value: '가성비',
  premium: '고급',
  solo: '혼밥',
  date: '데이트',
  'late-night': '야식',
  dessert: '디저트',
  cafe: '카페',
  vegan: '채식',
  drinks: '술안주',
  local: '로컬맛집',
};
